import type { CourseSpec } from "./types.js";

/* Python from Zero — 8 units, 40 lessons, ~240 exercises.

   AUTHORING CONSTRAINT: the in-browser runner cannot execute Python yet
   (runCode returns notImplemented for python, and the lesson runner hardcodes
   JavaScript), so this course deliberately uses only the exercise types that
   grade correctly without a runner — multiple_choice, fill_blank, arrange,
   predict_output and ai_prompt. No fix_bug or write_code here.

   Every solution below is genuine Python semantics: printed output, error
   names and method results are what CPython actually produces. When Pyodide
   lands, these exercises become the test cases for the runnable versions.

   Unicode tip: strings that contain Python double quotes use single-quoted TS
   literals so nothing needs escaping. */

export const pythonFromZero: CourseSpec = {
  slug: "python-from-zero",
  course: {
    title: "Python from Zero",
    language: "python",
    description:
      "From your first print() to real mastery — no prior code needed. Learn Python from scratch, one small step at a time.",
    order: 2,
  },
  units: [
    {
      title: "Unit 1 — Python Basics",
      description: "Print, variables and types — how a Python program behaves",
      lessons: [
        {
          title: "What Is Python?",
          description: "Running code and printing your first line",
          xpReward: 10,
          exercises: [
            { type: "multiple_choice", prompt: "What does print() do?", content: { options: ["Reads a file", "Shows text on the screen", "Creates a variable", "Sorts a list"], correctIndex: 1 }, solution: { correctIndex: 1 }, explanation: "print() sends text to the output — that is how Python talks back to you.", hints: ["Think 'show'."] },
            { type: "fill_blank", prompt: "Complete the line so it shows Hello", content: { code: '___("Hello")', blank: "print", options: ["print", "show", "echo", "write"] }, solution: { answer: "print" }, explanation: "print() is Python's way to show something.", hints: ["The word starts with p."] },
            { type: "predict_output", prompt: "What does this print?", content: { snippet: 'print("Hi")', options: ["Hi", "hi", "Hello", "Error"] }, solution: { answer: "Hi" }, explanation: "It prints exactly what is inside the quotes — case matters.", hints: ["Quotes are not printed."] },
            { type: "arrange", prompt: "Order these steps to run a Python program", content: { blocks: ["Write your code", "Run it", "See the output"] }, solution: { order: [0, 1, 2] }, explanation: "Write, run, then read the output.", hints: ["You write before you run."] },
            { type: "multiple_choice", prompt: "Which file extension do Python files use?", content: { options: [".py", ".python", ".pt", ".js"], correctIndex: 0 }, solution: { correctIndex: 0 }, explanation: "Python files end in .py.", hints: ["Two letters."] },
            { type: "predict_output", prompt: "What prints?", content: { snippet: 'print("Codingo")', options: ["Codingo", "codingo", "Console", "Error"] }, solution: { answer: "Codingo" }, explanation: "Case matters inside the quotes — copy it carefully.", hints: ["Capital C."] },
          ],
        },
        {
          title: "Your First Print",
          description: "Several values, comments and joining text",
          xpReward: 10,
          exercises: [
            { type: "fill_blank", prompt: "Show the number 42", content: { code: "print(___)", blank: "42", options: ["42", '"42"', "forty", "()"] }, solution: { answer: "42" }, explanation: "Numbers do not need quotes, so print(42) shows 42.", hints: ["Just the digits."] },
            { type: "predict_output", prompt: "What prints?", content: { snippet: 'print("a", "b")', options: ["a b", "ab", "a,b", "Error"] }, solution: { answer: "a b" }, explanation: "print() puts a single space between separate values.", hints: ["Something goes between them."] },
            { type: "multiple_choice", prompt: "How do you print on two separate lines?", content: { options: ["Call print() twice", "Call print(2)", "Write print twice on one line", "Call print(1, 2)"], correctIndex: 0 }, solution: { correctIndex: 0 }, explanation: "Each print() call starts a new line.", hints: ["Two calls."] },
            { type: "predict_output", prompt: "What prints?", content: { snippet: 'print("Hi " + "there")', options: ["Hi there", "Hithere", "Hi + there", "Error"] }, solution: { answer: "Hi there" }, explanation: "+ joins the strings and keeps the space that is inside the first one.", hints: ["The space is inside the quotes."] },
            { type: "arrange", prompt: "Order the lines to print a greeting", content: { blocks: ['name = "Ava"', 'print("Hi " + name)'] }, solution: { order: [0, 1] }, explanation: "Store the name first, then print using it.", hints: ["Declare before use."] },
            { type: "multiple_choice", prompt: "What starts a comment in Python?", content: { options: ["#", "//", "--", "/*"], correctIndex: 0 }, solution: { correctIndex: 0 }, explanation: "# starts a comment, and Python ignores the rest of the line.", hints: ["A hash."] },
          ],
        },
        {
          title: "Variables",
          description: "Storing values in names",
          xpReward: 10,
          exercises: [
            { type: "multiple_choice", prompt: "How do you create a variable in Python?", content: { options: ["x = 5", "let x = 5", "var x = 5;", "int x = 5"], correctIndex: 0 }, solution: { correctIndex: 0 }, explanation: "Just name = value. No keyword needed.", hints: ["No let or var."] },
            { type: "fill_blank", prompt: "Print the value stored in points", content: { code: "points = 100\nprint(___)", blank: "points", options: ["points", '"points"', "100", "None"] }, solution: { answer: "points" }, explanation: "Without quotes Python looks up the variable and prints 100. With quotes it would print the word points.", hints: ["No quotes."] },
            { type: "predict_output", prompt: "What prints?", content: { snippet: "x = 5\nprint(x)", options: ["5", "x", "None", "Error"] }, solution: { answer: "5" }, explanation: "The variable holds 5, so 5 is printed.", hints: ["Substitute the value."] },
            { type: "arrange", prompt: "Order these lines", content: { blocks: ["score = 0", "score = score + 10", "print(score)"] }, solution: { order: [0, 1, 2] }, explanation: "Create it, update it, then print it.", hints: ["Start at zero."] },
            { type: "multiple_choice", prompt: "Are variable names case-sensitive?", content: { options: ["Yes — score and Score are different names", "No, they are the same", "Only for numbers", "Only inside functions"], correctIndex: 0 }, solution: { correctIndex: 0 }, explanation: "Python treats score and Score as two entirely different names.", hints: ["Capital letters matter."] },
            { type: "multiple_choice", prompt: "What happens with 2name = 5?", content: { options: ["SyntaxError — a name cannot start with a digit", "It works fine", "It makes a string", "It prints 2"], correctIndex: 0 }, solution: { correctIndex: 0 }, explanation: "Names cannot begin with a number — that is a SyntaxError.", hints: ["Naming rules."] },
          ],
        },
        {
          title: "Types and type()",
          description: "int, float, str and bool",
          xpReward: 10,
          exercises: [
            { type: "multiple_choice", prompt: "type(5) returns?", content: { options: ["<class 'int'>", "int", "number", "<class 'float'>"], correctIndex: 0 }, solution: { correctIndex: 0 }, explanation: "Everything in Python is an object, so type() prints the class form.", hints: ["It mentions a class."] },
            { type: "predict_output", prompt: "What prints?", content: { snippet: 'print(type("hi"))', options: ["<class 'str'>", "<class 'int'>", "str", "Error"] }, solution: { answer: "<class 'str'>" }, explanation: "Text in quotes is a str (string).", hints: ["Letters mean str."] },
            { type: "fill_blank", prompt: "Print the type of 3.14", content: { code: "print(type(___))", blank: "3.14", options: ["3.14", '"3.14"', "int", "str"] }, solution: { answer: "3.14" }, explanation: "3.14 without quotes is a float, so this prints <class 'float'>.", hints: ["No quotes."] },
            { type: "multiple_choice", prompt: "Which value is a float?", content: { options: ["3.5", '"3.5"', "3", "True"], correctIndex: 0 }, solution: { correctIndex: 0 }, explanation: "A number with a decimal point is a float.", hints: ["Look for the dot."] },
            { type: "predict_output", prompt: "What prints?", content: { snippet: "print(type(True))", options: ["<class 'bool'>", "<class 'int'>", "bool", "Error"] }, solution: { answer: "<class 'bool'>" }, explanation: "True and False are bools.", hints: ["True is special."] },
            { type: "multiple_choice", prompt: "type(7) and type(7.0) are?", content: { options: ["int and float", "both int", "both float", "str and int"], correctIndex: 0 }, solution: { correctIndex: 0 }, explanation: "The decimal point is what makes it a float.", hints: ["The .0 matters."] },
          ],
        },
        {
          title: "Checkpoint: Basics",
          description: "Review Unit 1",
          xpReward: 15,
          exercises: [
            { type: "multiple_choice", prompt: "Which one shows text on the screen?", content: { options: ["print()", "show()", "echo()", "output()"], correctIndex: 0 }, solution: { correctIndex: 0 }, explanation: "print() is the real one.", hints: ["It is not show()."] },
            { type: "fill_blank", prompt: "Complete the line", content: { code: '___("Hello")', blank: "print", options: ["print", "input", "type", "int"] }, solution: { answer: "print" }, explanation: "print() shows text.", hints: ["Starts with p."] },
            { type: "predict_output", prompt: "What prints?", content: { snippet: "x = 3\nprint(x * 2)", options: ["6", "33", "x * 2", "Error"] }, solution: { answer: "6" }, explanation: "3 times 2 is 6.", hints: ["It multiplies."] },
            { type: "arrange", prompt: "Order these lines", content: { blocks: ['name = "Sam"', 'print("Hi", name)'] }, solution: { order: [0, 1] }, explanation: "Declare it, then print it.", hints: ["Value first."] },
            { type: "multiple_choice", prompt: 'type("5") is?', content: { options: ["<class 'str'>", "<class 'int'>", "<class 'float'>", "<class 'bool'>"], correctIndex: 0 }, solution: { correctIndex: 0 }, explanation: "Quotes make it a string, even though it looks like a number.", hints: ["Quotes win."] },
            { type: "predict_output", prompt: "What prints?", content: { snippet: "print(type(2.5))", options: ["<class 'float'>", "<class 'int'>", "<class 'str'>", "Error"] }, solution: { answer: "<class 'float'>" }, explanation: "A decimal point means float.", hints: ["Decimal means float."] },
          ],
        },
      ],
    },
    {
      title: "Unit 2 — Data & Strings",
      description: "Math, text, string methods and f-strings",
      lessons: [
        {
          title: "Numbers and Math",
          description: "+, -, *, /, //, % and **",
          xpReward: 10,
          exercises: [
            { type: "multiple_choice", prompt: "What is 7 // 2?", content: { options: ["3", "3.5", "4", "1"], correctIndex: 0 }, solution: { correctIndex: 0 }, explanation: "// is floor division: it drops the remainder, giving 3.", hints: ["Floor means round down."] },
            { type: "predict_output", prompt: "What prints?", content: { snippet: "print(7 % 2)", options: ["1", "0", "3", "3.5"] }, solution: { answer: "1" }, explanation: "% gives the remainder; 7 divided by 2 leaves 1.", hints: ["Remainder."] },
            { type: "fill_blank", prompt: "Print 10 to the power of 2", content: { code: "print(10 ** ___)", blank: "2", options: ["2", "10", "100", "*"] }, solution: { answer: "2" }, explanation: "** is power, so 10 ** 2 is 100.", hints: ["The exponent."] },
            { type: "predict_output", prompt: "What prints?", content: { snippet: "print(10 / 4)", options: ["2.5", "2", "2.0", "3"] }, solution: { answer: "2.5" }, explanation: "A single / always produces a float.", hints: ["Division keeps decimals."] },
            { type: "predict_output", prompt: "What prints?", content: { snippet: "print(5 + 3 * 2)", options: ["11", "16", "13", "10"] }, solution: { answer: "11" }, explanation: "* happens before +, so 3 * 2 is 6 and 5 + 6 is 11.", hints: ["Order of operations."] },
            { type: "multiple_choice", prompt: "Which operator gives the remainder?", content: { options: ["%", "//", "**", "/"], correctIndex: 0 }, solution: { correctIndex: 0 }, explanation: "% is modulo — it gives what is left over.", hints: ["Not a slash."] },
          ],
        },
        {
          title: "Strings Basics",
          description: "Joining text, len() and indexing",
          xpReward: 10,
          exercises: [
            { type: "multiple_choice", prompt: "How do you join two strings?", content: { options: ['"a" + "b"', '"a" . "b"', '"a" & "b"', '"a" ++ "b"'], correctIndex: 0 }, solution: { correctIndex: 0 }, explanation: "+ glues strings together.", hints: ["An arithmetic sign."] },
            { type: "predict_output", prompt: "What prints?", content: { snippet: 'print("Hi" + "there")', options: ["Hithere", "Hi there", "Hi+there", "Error"] }, solution: { answer: "Hithere" }, explanation: "+ adds nothing extra, so no space appears.", hints: ["No space is added."] },
            { type: "fill_blank", prompt: "Print how many characters are in python", content: { code: 'print(___("python"))', blank: "len", options: ["len", "size", "count", "length"] }, solution: { answer: "len" }, explanation: "len() counts characters and gives 6.", hints: ["Three letters."] },
            { type: "multiple_choice", prompt: 'len("hello") is?', content: { options: ["5", "4", "6", '"5"'], correctIndex: 0 }, solution: { correctIndex: 0 }, explanation: "Five characters.", hints: ["Count them."] },
            { type: "predict_output", prompt: "What prints?", content: { snippet: 'print("abc"[0])', options: ["a", "b", "c", "Error"] }, solution: { answer: "a" }, explanation: "Indexing starts at 0, so [0] is the first character.", hints: ["Start counting at zero."] },
            { type: "multiple_choice", prompt: 'For s = "code", what is s[1]?', content: { options: ["o", "c", "d", "e"], correctIndex: 0 }, solution: { correctIndex: 0 }, explanation: "[1] is the second character, o.", hints: ["Not the first one."] },
          ],
        },
        {
          title: "String Methods",
          description: "upper, lower, strip, split and replace",
          xpReward: 10,
          exercises: [
            { type: "multiple_choice", prompt: '"Hi".upper() gives?', content: { options: ["HI", "hi", "Hi", "Error"], correctIndex: 0 }, solution: { correctIndex: 0 }, explanation: "upper() makes every letter uppercase.", hints: ["All caps."] },
            { type: "predict_output", prompt: "What prints?", content: { snippet: 'print("Hi".lower())', options: ["hi", "HI", "Hi", "Error"] }, solution: { answer: "hi" }, explanation: "lower() makes it lowercase.", hints: ["Small letters."] },
            { type: "fill_blank", prompt: "Remove the extra spaces around the text", content: { code: 'print("  hi  ".___())', blank: "strip", options: ["strip", "trim", "clean", "cut"] }, solution: { answer: "strip" }, explanation: "strip() removes spaces from both ends, so this prints hi.", hints: ["It is not trim."] },
            { type: "multiple_choice", prompt: '"a,b".split(",") gives?', content: { options: ["['a', 'b']", "'a,b'", "['ab']", "('a','b')"], correctIndex: 0 }, solution: { correctIndex: 0 }, explanation: "split() breaks the string into a list of two pieces.", hints: ["It makes a list."] },
            { type: "predict_output", prompt: "What prints?", content: { snippet: 'print("hello".replace("l", "L"))', options: ["heLLo", "heLlo", "HeLLo", "hello"] }, solution: { answer: "heLLo" }, explanation: "Every l is replaced, so both of them become L.", hints: ["Both of them."] },
            { type: "fill_blank", prompt: "Make the text uppercase", content: { code: 'print("abc".___())', blank: "upper", options: ["upper", "up", "caps", "toUpperCase"] }, solution: { answer: "upper" }, explanation: "upper() uppercases the whole string.", hints: ["Not up()."] },
          ],
        },
        {
          title: "f-Strings",
          description: "Putting values inside text",
          xpReward: 10,
          exercises: [
            { type: "multiple_choice", prompt: "Which one is a valid f-string?", content: { options: ['f"Hi {name}"', '"Hi {name}"f', 'f"Hi name"', 'f"Hi" + {}'], correctIndex: 0 }, solution: { correctIndex: 0 }, explanation: "The f goes before the quote, and the variable goes inside the braces.", hints: ["f comes first."] },
            { type: "predict_output", prompt: "What prints?", content: { snippet: 'name = "Ava"\nprint(f"Hi {name}")', options: ["Hi Ava", "Hi {name}", "Hi name", "Error"] }, solution: { answer: "Hi Ava" }, explanation: "The braces are replaced by the value of name.", hints: ["Braces get replaced."] },
            { type: "fill_blank", prompt: "Complete the f-string so it prints the age", content: { code: 'age = 9\nprint(f"Age: {___}")', blank: "age", options: ["age", '"age"', "f", "9"] }, solution: { answer: "age" }, explanation: "Inside the braces you write the variable name, without quotes.", hints: ["No quotes inside braces."] },
            { type: "multiple_choice", prompt: "What do f-strings let you do?", content: { options: ["Put values inside a string", "Encrypt text", "Sort letters", "Only join two strings"], correctIndex: 0 }, solution: { correctIndex: 0 }, explanation: "They build text with values placed in it.", hints: ["It is about values."] },
            { type: "predict_output", prompt: "What prints?", content: { snippet: 'x = 4\nprint(f"{x} squared is {x*x}")', options: ["4 squared is 16", "4 squared is 44", "{x} squared is 16", "Error"] }, solution: { answer: "4 squared is 16" }, explanation: "Braces can hold expressions like x*x.", hints: ["x*x is 16."] },
            { type: "multiple_choice", prompt: "Which quotes work with f-strings?", content: { options: ["Single or double", "Only double", "Only single", "Triple only"], correctIndex: 0 }, solution: { correctIndex: 0 }, explanation: 'Both f"..." and f\'...\' work.', hints: ["Both simple quotes."] },
          ],
        },
        {
          title: "Checkpoint: Data and Strings",
          description: "Review Unit 2",
          xpReward: 15,
          exercises: [
            { type: "predict_output", prompt: "What prints?", content: { snippet: "print(9 // 2)", options: ["4", "4.5", "5", "1"] }, solution: { answer: "4" }, explanation: "Floor division drops the .5, giving 4.", hints: ["Round down."] },
            { type: "fill_blank", prompt: "Print the text in s, uppercased", content: { code: 's = "hey"\nprint(___)', blank: "s.upper()", options: ["s.upper()", "s", "upper(s)", '"s"'] }, solution: { answer: "s.upper()" }, explanation: "Call upper() on the variable itself.", hints: ["A method on s."] },
            { type: "multiple_choice", prompt: "Which one gives the number of characters?", content: { options: ["len(x)", "size(x)", "count(x)", "x.length"], correctIndex: 0 }, solution: { correctIndex: 0 }, explanation: "len() works on strings and lists.", hints: ["Three letters."] },
            { type: "predict_output", prompt: "What prints?", content: { snippet: 'print("go" + "od")', options: ["good", "go od", "g o o d", "Error"] }, solution: { answer: "good" }, explanation: "+ joins them with no space.", hints: ["No space."] },
            { type: "arrange", prompt: "Order these lines", content: { blocks: ['s = "Python"', "print(s.lower())"] }, solution: { order: [0, 1] }, explanation: "Assign it, then call the method.", hints: ["Value first."] },
            { type: "multiple_choice", prompt: 'f"{2+3}" prints?', content: { options: ["5", "2+3", "{2+3}", "Error"], correctIndex: 0 }, solution: { correctIndex: 0 }, explanation: "The braces evaluate the expression inside.", hints: ["It does the math."] },
          ],
        },
      ],
    },
    {
      title: "Unit 3 — Decisions",
      description: "Comparisons, branching, and combining conditions",
      lessons: [
        {
          title: "Booleans and Comparisons",
          description: "True, False, ==, != and friends",
          xpReward: 10,
          exercises: [
            { type: "predict_output", prompt: "What prints?", content: { snippet: "print(3 > 2)", options: ["True", "False", "true", "Error"] }, solution: { answer: "True" }, explanation: "True and False in Python both start with a capital letter.", hints: ["Capital T."] },
            { type: "multiple_choice", prompt: "Which operator checks equality?", content: { options: ["==", "=", "===", "eq"], correctIndex: 0 }, solution: { correctIndex: 0 }, explanation: "= assigns a value, == compares two values.", hints: ["Two equals signs."] },
            { type: "fill_blank", prompt: "Complete the comparison so it prints True", content: { code: "print(5 ___ 5)", blank: "==", options: ["==", "=", "!=", "<"] }, solution: { answer: "==" }, explanation: "Five equals five, so this prints True.", hints: ["You are comparing."] },
            { type: "predict_output", prompt: "What prints?", content: { snippet: "print(3 != 3)", options: ["False", "True", "Error", "None"] }, solution: { answer: "False" }, explanation: "!= means not equal. Since 3 does equal 3, the answer is False.", hints: ["They are equal."] },
            { type: "multiple_choice", prompt: "What type is the result of 4 > 1?", content: { options: ["bool", "int", "str", "float"], correctIndex: 0 }, solution: { correctIndex: 0 }, explanation: "Every comparison gives a bool.", hints: ["True is a bool."] },
            { type: "predict_output", prompt: "What prints?", content: { snippet: "print(10 >= 10)", options: ["True", "False", "10", "Error"] }, solution: { answer: "True" }, explanation: ">= means greater than or equal, and 10 does equal 10.", hints: ["Equal counts."] },
          ],
        },
        {
          title: "if / elif / else",
          description: "Making the program choose a path",
          xpReward: 10,
          exercises: [
            { type: "multiple_choice", prompt: "Which block runs only when the condition is True?", content: { options: ["the if block", "the else block", "both always", "neither"], correctIndex: 0 }, solution: { correctIndex: 0 }, explanation: "else is the fallback used when the test is False.", hints: ["Follow the test."] },
            { type: "predict_output", prompt: "What prints?", content: { snippet: 'x = 5\nif x > 3:\n    print("big")\nelse:\n    print("small")', options: ["big", "small", "True", "Error"] }, solution: { answer: "big" }, explanation: "5 is greater than 3, so the if block runs.", hints: ["5 beats 3."] },
            { type: "fill_blank", prompt: "Complete the line that starts the branch", content: { code: 'x = 2\n___ x > 1:\n    print("yes")', blank: "if", options: ["if", "when", "for", "while"] }, solution: { answer: "if" }, explanation: "if starts a conditional block, and the colon ends the line.", hints: ["Two letters."] },
            { type: "multiple_choice", prompt: "What does elif mean?", content: { options: ["else if", "end loop", "else print", "end function"], correctIndex: 0 }, solution: { correctIndex: 0 }, explanation: "elif checks another condition when the first one was False.", hints: ["Two words joined."] },
            { type: "predict_output", prompt: "What prints?", content: { snippet: 'x = 1\nif x == 0:\n    print("zero")\nelif x == 1:\n    print("one")\nelse:\n    print("other")', options: ["one", "zero", "other", "Error"] }, solution: { answer: "one" }, explanation: "x is 1, so the elif branch matches.", hints: ["Which branch fits?"] },
            { type: "multiple_choice", prompt: "How many else blocks can one if have?", content: { options: ["At most one", "Two", "Unlimited", "None"], correctIndex: 0 }, solution: { correctIndex: 0 }, explanation: "One else per if at each level.", hints: ["Just one."] },
            { type: "arrange", prompt: "Order these lines", content: { blocks: ["grade = 90", "if grade >= 50:", "    print(\"pass\")"] }, solution: { order: [0, 1, 2] }, explanation: "The body is indented under the if.", hints: ["Condition before body."] },
          ],
        },
        {
          title: "and, or, not",
          description: "Combining conditions",
          xpReward: 10,
          exercises: [
            { type: "predict_output", prompt: "What prints?", content: { snippet: "print(True and False)", options: ["False", "True", "Error", "None"] }, solution: { answer: "False" }, explanation: "and needs both sides to be True.", hints: ["Both must be True."] },
            { type: "predict_output", prompt: "What prints?", content: { snippet: "print(True or False)", options: ["True", "False", "Error", "None"] }, solution: { answer: "True" }, explanation: "or only needs one side to be True.", hints: ["One is enough."] },
            { type: "fill_blank", prompt: "Complete the line so it prints True", content: { code: "print(not ___)", blank: "False", options: ["False", "True", "0", "None"] }, solution: { answer: "False" }, explanation: "not flips the value, and not False is True.", hints: ["Flip it."] },
            { type: "multiple_choice", prompt: "x > 0 and x < 10 is True when?", content: { options: ["x is 5", "x is 20", "x is 0", "x is -1"], correctIndex: 0 }, solution: { correctIndex: 0 }, explanation: "5 sits between 0 and 10.", hints: ["It must be between."] },
            { type: "multiple_choice", prompt: "What is not True?", content: { options: ["False", "True", "None", "Error"], correctIndex: 0 }, solution: { correctIndex: 0 }, explanation: "not flips True into False.", hints: ["The opposite."] },
            { type: "predict_output", prompt: "What prints?", content: { snippet: "print(2 > 1 and 1 > 2)", options: ["False", "True", "Error", "None"] }, solution: { answer: "False" }, explanation: "The second half is False, so the whole and is False.", hints: ["One side fails."] },
          ],
        },
        {
          title: "Truthiness and None",
          description: "What counts as falsy, and what None means",
          xpReward: 10,
          exercises: [
            { type: "multiple_choice", prompt: "bool(0) is?", content: { options: ["False", "True", "0", "Error"], correctIndex: 0 }, solution: { correctIndex: 0 }, explanation: "Zero is falsy.", hints: ["Zero."] },
            { type: "predict_output", prompt: "What prints?", content: { snippet: 'print(bool(""))', options: ["False", "True", '""', "Error"] }, solution: { answer: "False" }, explanation: "An empty string is falsy.", hints: ["It is empty."] },
            { type: "fill_blank", prompt: "Check that x is the special no-value object", content: { code: "x = None\nprint(x is ___)", blank: "None", options: ["None", "none", "NULL", "null"] }, solution: { answer: "None" }, explanation: "None is written with a capital N.", hints: ["Capital N."] },
            { type: "multiple_choice", prompt: "Which value is falsy?", content: { options: ["[]", "[1]", '"hi"', "3"], correctIndex: 0 }, solution: { correctIndex: 0 }, explanation: "An empty list is falsy, while a non-empty container is truthy.", hints: ["The empty one."] },
            { type: "predict_output", prompt: "What prints?", content: { snippet: 'print(bool("0"))', options: ["True", "False", "0", "Error"] }, solution: { answer: "True" }, explanation: 'A non-empty string is truthy — even "0", because it still has a character.', hints: ["Is it empty?"] },
            { type: "multiple_choice", prompt: "None means?", content: { options: ["No value", "zero", "empty text", "False"], correctIndex: 0 }, solution: { correctIndex: 0 }, explanation: "None is the absence of a value.", hints: ["Nothing is there."] },
          ],
        },
        {
          title: "Checkpoint: Decisions",
          description: "Review Unit 3",
          xpReward: 15,
          exercises: [
            { type: "predict_output", prompt: "What prints?", content: { snippet: "x = 7\nprint(x % 2 == 1)", options: ["True", "False", "1", "Error"] }, solution: { answer: "True" }, explanation: "7 % 2 is 1, and 1 == 1 is True.", hints: ["It is odd."] },
            { type: "fill_blank", prompt: "Handle the case the if did not catch", content: { code: 'x = 4\nif x > 10:\n    print("big")\n___:\n    print("small")', blank: "else", options: ["else", "elif", "then", "end"] }, solution: { answer: "else" }, explanation: "else catches everything the if did not.", hints: ["It needs no condition."] },
            { type: "multiple_choice", prompt: "Which expression is True?", content: { options: ["3 < 5 and 5 < 9", "3 > 5", "not 1", "0 and 1"], correctIndex: 0 }, solution: { correctIndex: 0 }, explanation: "Both parts hold, so the and is True.", hints: ["Both halves must hold."] },
            { type: "arrange", prompt: "Order these lines", content: { blocks: ['age = 18', 'if age >= 18:', '    print("adult")'] }, solution: { order: [0, 1, 2] }, explanation: "Condition first, then the indented body.", hints: ["Condition, then body."] },
            { type: "predict_output", prompt: "What prints?", content: { snippet: "print(not (2 > 1))", options: ["False", "True", "Error", "None"] }, solution: { answer: "False" }, explanation: "2 > 1 is True, and not True is False.", hints: ["Do the inside first."] },
            { type: "multiple_choice", prompt: "Indentation in Python is?", content: { options: ["Required — it defines blocks", "Optional", "Only for comments", "Only inside loops"], correctIndex: 0 }, solution: { correctIndex: 0 }, explanation: "Python uses indentation where other languages use braces.", hints: ["It is not optional."] },
          ],
        },
      ],
    },
    {
      title: "Unit 4 — Loops",
      description: "Repeating work with for and while",
      lessons: [
        {
          title: "for Loops and range()",
          description: "Repeating work a set number of times",
          xpReward: 10,
          exercises: [
            { type: "multiple_choice", prompt: "range(3) produces?", content: { options: ["0, 1, 2", "1, 2, 3", "0, 1, 2, 3", "3"], correctIndex: 0 }, solution: { correctIndex: 0 }, explanation: "range stops before the number you give it.", hints: ["It starts at 0."] },
            { type: "predict_output", prompt: "What prints?", content: { snippet: "total = 0\nfor i in range(3):\n    total = total + i\nprint(total)", options: ["3", "6", "2", "0"] }, solution: { answer: "3" }, explanation: "0 + 1 + 2 is 3.", hints: ["Add them all up."] },
            { type: "fill_blank", prompt: "Make the loop print 0, 1, 2 and 3", content: { code: "for i in range(___):\n    print(i)", blank: "4", options: ["4", "3", "5", "0"] }, solution: { answer: "4" }, explanation: "range(4) gives 0 up to 3.", hints: ["Count the values you need."] },
            { type: "multiple_choice", prompt: "range(1, 4) gives?", content: { options: ["1, 2, 3", "1, 2, 3, 4", "0, 1, 2, 3", "2, 3, 4"], correctIndex: 0 }, solution: { correctIndex: 0 }, explanation: "The start is included and the end is not.", hints: ["The end is excluded."] },
            { type: "predict_output", prompt: "What prints?", content: { snippet: "print(list(range(3)))", options: ["[0, 1, 2]", "[1, 2, 3]", "0 1 2", "range(3)"] }, solution: { answer: "[0, 1, 2]" }, explanation: "list() shows you what range produces.", hints: ["Square brackets."] },
            { type: "multiple_choice", prompt: "Which one loops over each item of xs?", content: { options: ["for x in xs:", "for xs in x:", "loop xs", "for (x in xs)"], correctIndex: 0 }, solution: { correctIndex: 0 }, explanation: "for x in xs visits every item in turn.", hints: ["Value then collection."] },
          ],
        },
        {
          title: "Looping Strings and Lists",
          description: "for over characters and items, with an accumulator",
          xpReward: 10,
          exercises: [
            { type: "multiple_choice", prompt: 'for c in "abc" runs the body how many times?', content: { options: ["3", "2", "1", "4"], correctIndex: 0 }, solution: { correctIndex: 0 }, explanation: "One run per character.", hints: ["Three characters."] },
            { type: "predict_output", prompt: "What prints?", content: { snippet: 'for c in "abc":\n    print(c)', options: ["a\nb\nc", "abc", "c\nb\na", "Error"] }, solution: { answer: "a\nb\nc" }, explanation: "One character per line, in order.", hints: ["One line each."] },
            { type: "fill_blank", prompt: "Print each number in the list", content: { code: "for n in [1, 2, 3]:\n    print(___)", blank: "n", options: ["n", "1", "n()", "list"] }, solution: { answer: "n" }, explanation: "n holds the current item on each pass.", hints: ["The loop variable."] },
            { type: "predict_output", prompt: "What prints?", content: { snippet: "total = 0\nfor n in [1, 2, 3]:\n    total = total + n\nprint(total)", options: ["6", "3", "123", "Error"] }, solution: { answer: "6" }, explanation: "1 + 2 + 3 is 6.", hints: ["Add all three."] },
            { type: "multiple_choice", prompt: "Looping a string gives you?", content: { options: ["One character at a time", "Whole words", "Bytes", "Nothing"], correctIndex: 0 }, solution: { correctIndex: 0 }, explanation: "A string is a sequence of characters.", hints: ["The smallest pieces."] },
            { type: "arrange", prompt: "Order these lines", content: { blocks: ["for n in [1, 2]:", "    print(n)"] }, solution: { order: [0, 1] }, explanation: "The body is indented under the for.", hints: ["The body goes second."] },
          ],
        },
        {
          title: "while Loops",
          description: "Repeat until a condition stops being true",
          xpReward: 10,
          exercises: [
            { type: "multiple_choice", prompt: "A while loop repeats?", content: { options: ["While its condition stays True", "Exactly 3 times", "Forever, always", "Only once"], correctIndex: 0 }, solution: { correctIndex: 0 }, explanation: "You must change something so the condition eventually becomes False.", hints: ["It depends on a condition."] },
            { type: "predict_output", prompt: "What prints?", content: { snippet: "n = 0\nwhile n < 2:\n    n = n + 1\nprint(n)", options: ["2", "1", "0", "3"] }, solution: { answer: "2" }, explanation: "It stops as soon as n reaches 2.", hints: ["Where does it stop?"] },
            { type: "fill_blank", prompt: "Count down to 0", content: { code: "n = 3\nwhile n > 0:\n    n = n - ___", blank: "1", options: ["1", "0", "2", "n"] }, solution: { answer: "1" }, explanation: "Subtracting 1 each time gets you to 0.", hints: ["One step at a time."] },
            { type: "multiple_choice", prompt: "An infinite loop happens when?", content: { options: ["The condition never becomes False", "You use while", "You use range", "You call print"], correctIndex: 0 }, solution: { correctIndex: 0 }, explanation: "If nothing changes, the loop never ends.", hints: ["Nothing changes."] },
            { type: "predict_output", prompt: "What prints?", content: { snippet: "n = 0\nwhile n < 3:\n    n = n + 1\nprint(n)", options: ["3", "2", "0", "Error"] }, solution: { answer: "3" }, explanation: "n grows until it reaches 3, then the loop stops.", hints: ["Look at the limit."] },
            { type: "multiple_choice", prompt: "Which while line is valid Python?", content: { options: ["while n < 5:", "while (n < 5)", "while n < 5 do", "while n < 5 then"], correctIndex: 0 }, solution: { correctIndex: 0 }, explanation: "The colon ends the line.", hints: ["Colon at the end."] },
          ],
        },
        {
          title: "break and continue",
          description: "Leaving early and skipping one round",
          xpReward: 10,
          exercises: [
            { type: "multiple_choice", prompt: "What does break do?", content: { options: ["Leaves the loop immediately", "Skips one round", "Restarts the loop", "Pauses the program"], correctIndex: 0 }, solution: { correctIndex: 0 }, explanation: "break exits the loop completely.", hints: ["It ends the loop."] },
            { type: "multiple_choice", prompt: "What does continue do?", content: { options: ["Skips to the next round", "Ends the loop", "Ends the program", "Prints the value"], correctIndex: 0 }, solution: { correctIndex: 0 }, explanation: "continue jumps to the next iteration without ending the loop.", hints: ["It does not end the loop."] },
            { type: "predict_output", prompt: "What prints?", content: { snippet: "for i in range(5):\n    if i == 2:\n        break\nprint(i)", options: ["2", "1", "5", "Error"] }, solution: { answer: "2" }, explanation: "The loop stops when i is 2, and the print after the loop sees i still holding 2.", hints: ["What is i at the moment it stops?"] },
            { type: "predict_output", prompt: "What prints?", content: { snippet: "count = 0\nfor i in range(4):\n    if i == 1:\n        continue\n    count = count + 1\nprint(count)", options: ["3", "4", "2", "1"] }, solution: { answer: "3" }, explanation: "The round where i is 1 is skipped, so only 3 rounds count.", hints: ["One round is skipped."] },
            { type: "fill_blank", prompt: "Stop the loop when i reaches 3", content: { code: "for i in range(5):\n    if i == 3:\n        ___", blank: "break", options: ["break", "continue", "stop", "exit"] }, solution: { answer: "break" }, explanation: "break leaves the loop at i = 3.", hints: ["Not continue."] },
            { type: "multiple_choice", prompt: "Which pair controls loop flow?", content: { options: ["break and continue", "stop and skip", "halt and next", "exit and pass"], correctIndex: 0 }, solution: { correctIndex: 0 }, explanation: "break leaves the loop, continue skips a round.", hints: ["The real keywords."] },
          ],
        },
        {
          title: "Checkpoint: Loops",
          description: "Review Unit 4",
          xpReward: 15,
          exercises: [
            { type: "predict_output", prompt: "What prints?", content: { snippet: "print(list(range(2, 5)))", options: ["[2, 3, 4]", "[2, 3, 4, 5]", "[3, 4]", "Error"] }, solution: { answer: "[2, 3, 4]" }, explanation: "Start at 2 and stop before 5.", hints: ["The end is excluded."] },
            { type: "fill_blank", prompt: "Print the running total", content: { code: "total = 0\nfor n in [2, 3]:\n    total = total + n\nprint(___)", blank: "total", options: ["total", "n", "2", "sum"] }, solution: { answer: "total" }, explanation: "total holds 5 by the end.", hints: ["The accumulator."] },
            { type: "multiple_choice", prompt: "range(3) starts at?", content: { options: ["0", "1", "3", "-3"], correctIndex: 0 }, solution: { correctIndex: 0 }, explanation: "The default start is 0.", hints: ["Zero."] },
            { type: "predict_output", prompt: "What prints?", content: { snippet: "n = 0\nwhile n < 2:\n    n = n + 1\nprint(n)", options: ["2", "1", "0", "3"] }, solution: { answer: "2" }, explanation: "n finishes at 2.", hints: ["The stopping value."] },
            { type: "arrange", prompt: "Order these lines", content: { blocks: ["total = 0", "for n in [1, 2]:", "    total = total + n", "print(total)"] }, solution: { order: [0, 1, 2, 3] }, explanation: "Set up, loop, accumulate, then print.", hints: ["Set up first."] },
            { type: "multiple_choice", prompt: "How many times does for i in range(4) run?", content: { options: ["4", "3", "5", "1"], correctIndex: 0 }, solution: { correctIndex: 0 }, explanation: "0, 1, 2 and 3 — four runs.", hints: ["Count 0, 1, 2, 3."] },
          ],
        },
      ],
    },
    {
      title: "Unit 5 — Functions",
      description: "Reusable blocks of behaviour",
      lessons: [
        {
          title: "Defining Functions",
          description: "def, calling, and why functions help",
          xpReward: 15,
          exercises: [
            { type: "multiple_choice", prompt: "Which one defines a function?", content: { options: ["def greet():", "function greet()", "greet = def()", "fun greet()"], correctIndex: 0 }, solution: { correctIndex: 0 }, explanation: "def, then the name, then parentheses and a colon.", hints: ["Three letters."] },
            { type: "fill_blank", prompt: "Complete the function definition", content: { code: '___ hello():\n    print("hi")', blank: "def", options: ["def", "function", "fun", "func"] }, solution: { answer: "def" }, explanation: "def starts a function definition.", hints: ["Not function."] },
            { type: "multiple_choice", prompt: "To actually run the function greet you write?", content: { options: ["greet()", "call greet", "greet[]", "run greet()"], correctIndex: 0 }, solution: { correctIndex: 0 }, explanation: "Adding () calls it.", hints: ["Parentheses."] },
            { type: "predict_output", prompt: "What prints?", content: { snippet: 'def hi():\n    print("hi")\nhi()', options: ["hi", "hi()", "None", "Error"] }, solution: { answer: "hi" }, explanation: "The body runs only when you call hi().", hints: ["The call runs it."] },
            { type: "multiple_choice", prompt: "Why use functions?", content: { options: ["To reuse code and keep it readable", "To make files bigger", "To slow the program down", "Only for math"], correctIndex: 0 }, solution: { correctIndex: 0 }, explanation: "Write it once, call it many times.", hints: ["Reuse."] },
            { type: "arrange", prompt: "Order these lines", content: { blocks: ['def hi():', '    print("hi")', "hi()"] }, solution: { order: [0, 1, 2] }, explanation: "Define it first, then call it.", hints: ["The call is last."] },
            { type: "ai_prompt", prompt: "Ask the AI to explain a function", content: { scenario: 'Your mission: paste this code and ask the AI to explain what it does in one or two simple lines: def greet(name): return "Hi " + name', aiTask: "You are Codingo, a friendly tutor for absolute beginners. Explain the learner's Python function in under 60 words, plain language, zero jargon. The learner asked:", placeholder: 'e.g. Explain what this does: def greet(name): return "Hi " + name', checklist: ["Did it mention the function hands back a greeting with the name?", "Was it short and free of jargon?"], exampleAnswer: 'This function takes a name, like Ava, and gives back the text "Hi Ava". The word return means it hands that text back to whoever called it.' }, solution: { checklist: [true, true] }, explanation: "Now you know what defining and returning really mean.", hints: ["Say: explain it in one or two lines."] },
          ],
        },
        {
          title: "Parameters and Return",
          description: "Inputs and outputs of a function",
          xpReward: 15,
          exercises: [
            { type: "multiple_choice", prompt: "Which function takes one parameter?", content: { options: ["def greet(name):", "def greet():", "def greet:name", "def greet(name)"], correctIndex: 0 }, solution: { correctIndex: 0 }, explanation: "The name inside the parentheses is the parameter.", hints: ["Look inside the parentheses."] },
            { type: "fill_blank", prompt: "Hand the doubled number back to the caller", content: { code: "def double(n):\n    ___ n * 2\nprint(double(4))", blank: "return", options: ["return", "print", "give", "out"] }, solution: { answer: "return" }, explanation: "return sends the value back, and then 8 is printed.", hints: ["Six letters."] },
            { type: "predict_output", prompt: "What prints?", content: { snippet: "def add(a, b):\n    return a + b\nprint(add(2, 3))", options: ["5", "23", "a + b", "None"] }, solution: { answer: "5" }, explanation: "The arguments 2 and 3 fill a and b.", hints: ["Add them."] },
            { type: "multiple_choice", prompt: "A function without return gives you?", content: { options: ["None", "0", '""', "Error"], correctIndex: 0 }, solution: { correctIndex: 0 }, explanation: "Python returns None when there is nothing to return.", hints: ["It is not zero."] },
            { type: "predict_output", prompt: "What prints?", content: { snippet: "def f(x):\n    return x * 3\nprint(f(2) + 1)", options: ["7", "6", "21", "Error"] }, solution: { answer: "7" }, explanation: "f(2) is 6, then 6 + 1 is 7.", hints: ["Multiply first."] },
            { type: "multiple_choice", prompt: "What does return do?", content: { options: ["Sends a value back to the caller", "Prints to the screen", "Stops Python", "Creates a variable"], correctIndex: 0 }, solution: { correctIndex: 0 }, explanation: "The value comes back to where the function was called.", hints: ["Back to the caller."] },
          ],
        },
        {
          title: "Default and Keyword Arguments",
          description: "Optional values and named arguments",
          xpReward: 15,
          exercises: [
            { type: "multiple_choice", prompt: "Which one defines a default value?", content: { options: ['def greet(name="friend"):', "def greet(name):", 'def greet("friend"):', "def greet(name =):"], correctIndex: 0 }, solution: { correctIndex: 0 }, explanation: 'name="friend" makes that argument optional.', hints: ["An equals sign inside the parentheses."] },
            { type: "predict_output", prompt: "What prints?", content: { snippet: 'def greet(name="friend"):\n    print(name)\ngreet()', options: ["friend", "name", "None", "Error"] }, solution: { answer: "friend" }, explanation: "With no argument passed, the default is used.", hints: ["The default it is."] },
            { type: "fill_blank", prompt: "Make power(2) return 4", content: { code: "def power(base, exp=___):\n    return base ** exp\nprint(power(2))", blank: "2", options: ["2", "1", "0", "exp"] }, solution: { answer: "2" }, explanation: "A default exponent of 2 squares the base.", hints: ["Squared."] },
            { type: "multiple_choice", prompt: 'greet(name="Ava") uses?', content: { options: ["A keyword argument", "A loop", "Only a default", "A list"], correctIndex: 0 }, solution: { correctIndex: 0 }, explanation: "Naming the argument like that is a keyword argument.", hints: ["It names the value."] },
            { type: "predict_output", prompt: "What prints?", content: { snippet: "def show(a, b=2):\n    print(a + b)\nshow(1, 5)", options: ["6", "3", "15", "Error"] }, solution: { answer: "6" }, explanation: "You passed 5, so the default is ignored.", hints: ["Your value wins."] },
            { type: "multiple_choice", prompt: "Parameters with defaults must come?", content: { options: ["After the ones without defaults", "Before them", "Anywhere", "Only inside classes"], correctIndex: 0 }, solution: { correctIndex: 0 }, explanation: "Otherwise Python cannot tell which argument you meant.", hints: ["Order matters."] },
          ],
        },
        {
          title: "Scope",
          description: "Where names live and when they disappear",
          xpReward: 15,
          exercises: [
            { type: "multiple_choice", prompt: "A variable created inside a function is?", content: { options: ["Local to that function", "Global everywhere", "Deleted instantly", "Always shared"], correctIndex: 0 }, solution: { correctIndex: 0 }, explanation: "It exists only while the function runs.", hints: ["Only inside."] },
            { type: "predict_output", prompt: "What prints?", content: { snippet: "x = 1\ndef f():\n    x = 2\nf()\nprint(x)", options: ["1", "2", "None", "Error"] }, solution: { answer: "1" }, explanation: "The x inside f is a separate local name, so the outer x stays 1.", hints: ["Two different x names."] },
            { type: "fill_blank", prompt: "Return the local value", content: { code: "def f():\n    ___ = 5\n    return n\nprint(f())", blank: "n", options: ["n", "y", "x", "f"] }, solution: { answer: "n" }, explanation: "The name must match what return sends back.", hints: ["Match the return statement."] },
            { type: "multiple_choice", prompt: "Which keyword lets a function write to a global name?", content: { options: ["global", "outer", "public", "shared"], correctIndex: 0 }, solution: { correctIndex: 0 }, explanation: "You have to opt in explicitly with global.", hints: ["Six letters."] },
            { type: "multiple_choice", prompt: "Local scope means?", content: { options: ["Only that function can see the name", "Everybody can see it", "It is stored on disk", "It is temporary text"], correctIndex: 0 }, solution: { correctIndex: 0 }, explanation: "Names are hidden from the outside.", hints: ["Hidden outside."] },
            { type: "predict_output", prompt: "What prints?", content: { snippet: "def f():\n    return 5\nprint(f() + f())", options: ["10", "5", "55", "Error"] }, solution: { answer: "10" }, explanation: "Each call returns 5, so 5 + 5 is 10.", hints: ["There are two calls."] },
          ],
        },
        {
          title: "Checkpoint: Functions",
          description: "Review Unit 5",
          xpReward: 15,
          exercises: [
            { type: "fill_blank", prompt: "Complete the function definition", content: { code: "___ square(n):\n    return n * n\nprint(square(4))", blank: "def", options: ["def", "fun", "function", "lambda"] }, solution: { answer: "def" }, explanation: "def defines it, and square(4) gives 16.", hints: ["Three letters."] },
            { type: "predict_output", prompt: "What prints?", content: { snippet: 'def lab(n):\n    return "n is " + str(n)\nprint(lab(3))', options: ["n is 3", "n is n", "3", "Error"] }, solution: { answer: "n is 3" }, explanation: "str(n) turns the number into text so it can be joined to the string.", hints: ["The number becomes text."] },
            { type: "multiple_choice", prompt: "def and return are?", content: { options: ["Keywords", "Functions", "Variables", "Strings"], correctIndex: 0 }, solution: { correctIndex: 0 }, explanation: "They are part of the language itself.", hints: ["Built into Python."] },
            { type: "predict_output", prompt: "What prints?", content: { snippet: "def f(a, b=1):\n    return a * b\nprint(f(4))", options: ["4", "5", "41", "Error"] }, solution: { answer: "4" }, explanation: "The default b is 1, so 4 * 1 is 4.", hints: ["Times one."] },
            { type: "multiple_choice", prompt: "A function's body runs?", content: { options: ["When you call the function", "Always at startup", "Exactly once ever", "Never"], correctIndex: 0 }, solution: { correctIndex: 0 }, explanation: "Defining a function does not run it.", hints: ["On the call."] },
            { type: "arrange", prompt: "Order these lines", content: { blocks: ["def cube(n):", "    return n ** 3", "print(cube(2))"] }, solution: { order: [0, 1, 2] }, explanation: "Define it, then call it and print 8.", hints: ["The definition comes first."] },
          ],
        },
      ],
    },
    {
      title: "Unit 6 — Collections",
      description: "Lists, tuples and dictionaries",
      lessons: [
        {
          title: "Lists",
          description: "Ordered, changeable groups of values",
          xpReward: 15,
          exercises: [
            { type: "multiple_choice", prompt: "Which one makes a list?", content: { options: ["[1, 2, 3]", "(1, 2, 3)", "{1, 2, 3}", '"1, 2, 3"'], correctIndex: 0 }, solution: { correctIndex: 0 }, explanation: "Square brackets make a list.", hints: ["Square brackets."] },
            { type: "predict_output", prompt: "What prints?", content: { snippet: "xs = [10, 20, 30]\nprint(xs[1])", options: ["20", "10", "30", "Error"] }, solution: { answer: "20" }, explanation: "Index 1 is the second item.", hints: ["Count from 0."] },
            { type: "fill_blank", prompt: "Add 3 to the end of the list", content: { code: "xs = [1, 2]\nxs.___(3)\nprint(len(xs))", blank: "append", options: ["append", "add", "push", "insert"] }, solution: { answer: "append" }, explanation: "append adds one item to the end, so len becomes 3.", hints: ["It is not push."] },
            { type: "predict_output", prompt: "What prints?", content: { snippet: "xs = [1, 2, 3]\nprint(len(xs))", options: ["3", "2", "4", "Error"] }, solution: { answer: "3" }, explanation: "There are three items in the list.", hints: ["Count them."] },
            { type: "multiple_choice", prompt: "Lists are?", content: { options: ["Ordered and changeable", "Fixed in size", "Only for numbers", "Always sorted"], correctIndex: 0 }, solution: { correctIndex: 0 }, explanation: "You can add, remove and reorder items.", hints: ["You can change them."] },
            { type: "predict_output", prompt: "What prints?", content: { snippet: "xs = [1, 2, 3]\nprint(xs[-1])", options: ["3", "1", "2", "Error"] }, solution: { answer: "3" }, explanation: "Negative indexes count from the end, so -1 is the last item.", hints: ["Count from the back."] },
          ],
        },
        {
          title: "List Methods and Slicing",
          description: "Slices, sort, pop and sum",
          xpReward: 15,
          exercises: [
            { type: "multiple_choice", prompt: "xs[0:2] gives?", content: { options: ["The first two items", "Items 0 and 2", "The last two", "Every item"], correctIndex: 0 }, solution: { correctIndex: 0 }, explanation: "The end of a slice is not included.", hints: ["The end is excluded."] },
            { type: "predict_output", prompt: "What prints?", content: { snippet: "xs = [1, 2, 3, 4]\nprint(xs[:2])", options: ["[1, 2]", "[2, 3]", "[1, 2, 3]", "[3, 4]"] }, solution: { answer: "[1, 2]" }, explanation: "From the start up to but not including index 2.", hints: ["Two items."] },
            { type: "fill_blank", prompt: "Sort the list so the smallest comes first", content: { code: "xs = [3, 1, 2]\nxs.___()\nprint(xs[0])", blank: "sort", options: ["sort", "order", "sorted", "arrange"] }, solution: { answer: "sort" }, explanation: "sort() reorders the list in place, so xs[0] becomes 1.", hints: ["It is not sorted."] },
            { type: "predict_output", prompt: "What prints?", content: { snippet: "xs = [1, 2, 3]\nxs.pop()\nprint(xs)", options: ["[1, 2]", "[2, 3]", "[1, 2, 3]", "3"] }, solution: { answer: "[1, 2]" }, explanation: "pop() removes and returns the last item.", hints: ["The last one goes."] },
            { type: "multiple_choice", prompt: "xs.append(x) does what?", content: { options: ["Adds x to the end", "Removes x", "Sorts x", "Counts x"], correctIndex: 0 }, solution: { correctIndex: 0 }, explanation: "It grows the list by one item.", hints: ["It grows the list."] },
            { type: "predict_output", prompt: "What prints?", content: { snippet: "print(sum([1, 2, 3]))", options: ["6", "123", "3", "[6]"] }, solution: { answer: "6" }, explanation: "sum() adds the numbers together.", hints: ["Add them."] },
          ],
        },
        {
          title: "Tuples",
          description: "Ordered but unchangeable",
          xpReward: 15,
          exercises: [
            { type: "multiple_choice", prompt: "Which one makes a tuple?", content: { options: ["(1, 2)", "[1, 2]", "{1, 2}", "{1: 2}"], correctIndex: 0 }, solution: { correctIndex: 0 }, explanation: "Round brackets make a tuple.", hints: ["Round brackets."] },
            { type: "predict_output", prompt: "What prints?", content: { snippet: "t = (1, 2)\nprint(t[0])", options: ["1", "2", "(1, 2)", "Error"] }, solution: { answer: "1" }, explanation: "Indexing works exactly like it does for lists.", hints: ["The first item."] },
            { type: "multiple_choice", prompt: "Tuples are?", content: { options: ["Ordered and unchangeable", "Changeable", "Unordered", "Only for strings"], correctIndex: 0 }, solution: { correctIndex: 0 }, explanation: "Once created, a tuple cannot be modified.", hints: ["You cannot change them."] },
            { type: "fill_blank", prompt: "Unpack the tuple, then print the first value", content: { code: "point = (3, 4)\nx, y = point\nprint(___)", blank: "x", options: ["x", "point", "3", "tuple"] }, solution: { answer: "x" }, explanation: "Unpacking puts 3 into x and 4 into y.", hints: ["The first name."] },
            { type: "multiple_choice", prompt: "What happens with t[0] = 9 on a tuple?", content: { options: ["TypeError — tuples cannot be changed", "The value updates", "It prints it", "It sorts it"], correctIndex: 0 }, solution: { correctIndex: 0 }, explanation: "Tuples are immutable.", hints: ["They are fixed."] },
            { type: "predict_output", prompt: "What prints?", content: { snippet: "t = (1, 2, 3)\nprint(len(t))", options: ["3", "2", "(1, 2, 3)", "Error"] }, solution: { answer: "3" }, explanation: "len() works on tuples too.", hints: ["Count them."] },
          ],
        },
        {
          title: "Dictionaries",
          description: "Looking things up by key",
          xpReward: 15,
          exercises: [
            { type: "multiple_choice", prompt: "Which one makes a dictionary?", content: { options: ['{"a": 1}', '["a", 1]', '("a", 1)', '{"a", 1}'], correctIndex: 0 }, solution: { correctIndex: 0 }, explanation: "Curly braces with key: value pairs.", hints: ["Key and value."] },
            { type: "predict_output", prompt: "What prints?", content: { snippet: 'd = {"a": 1}\nprint(d["a"])', options: ["1", "a", '{"a": 1}', "Error"] }, solution: { answer: "1" }, explanation: "You look up a key to get its value.", hints: ["The value side."] },
            { type: "fill_blank", prompt: "Look the key up safely", content: { code: 'd = {"a": 1}\nprint(d.___("a"))', blank: "get", options: ["get", "find", "read", "at"] }, solution: { answer: "get" }, explanation: "get() gives the value, and None instead of crashing when the key is missing.", hints: ["Three letters."] },
            { type: "predict_output", prompt: "What prints?", content: { snippet: 'd = {"a": 1, "b": 2}\nprint(len(d))', options: ["2", "1", '{"a": 1, "b": 2}', "Error"] }, solution: { answer: "2" }, explanation: "len() counts the pairs.", hints: ["Two pairs."] },
            { type: "multiple_choice", prompt: "A dictionary maps?", content: { options: ["Keys to values", "Indexes to items", "Letters to numbers only", "Files to folders"], correctIndex: 0 }, solution: { correctIndex: 0 }, explanation: "You look values up by key.", hints: ["Key to value."] },
            { type: "predict_output", prompt: "What prints?", content: { snippet: 'd = {}\nd["n"] = 5\nprint(d["n"])', options: ["5", "0", "None", "Error"] }, solution: { answer: "5" }, explanation: "Assigning a new key adds it to the dictionary.", hints: ["It was just added."] },
          ],
        },
        {
          title: "Checkpoint: Collections",
          description: "Review Unit 6",
          xpReward: 15,
          exercises: [
            { type: "multiple_choice", prompt: "Which one is changeable?", content: { options: ["list", "tuple", "string", "int"], correctIndex: 0 }, solution: { correctIndex: 0 }, explanation: "Only the list can be modified in place.", hints: ["The mutable one."] },
            { type: "predict_output", prompt: "What prints?", content: { snippet: "xs = [1, 2]\nxs.append(3)\nprint(len(xs))", options: ["3", "2", "[1, 2, 3]", "Error"] }, solution: { answer: "3" }, explanation: "append made the list three items long.", hints: ["It grew."] },
            { type: "fill_blank", prompt: "Print the value stored under key k", content: { code: 'd = {"k": 7}\nprint(d[___])', blank: '"k"', options: ['"k"', "k", "7", "get"] }, solution: { answer: '"k"' }, explanation: "The key is a string here, so it needs quotes inside the brackets.", hints: ["Quotes are required."] },
            { type: "predict_output", prompt: "What prints?", content: { snippet: "print(sorted([3, 1, 2]))", options: ["[1, 2, 3]", "[3, 2, 1]", "3", "Error"] }, solution: { answer: "[1, 2, 3]" }, explanation: "sorted() returns a new list, smallest first.", hints: ["Smallest first."] },
            { type: "arrange", prompt: "Order these lines", content: { blocks: ["xs = [1, 2]", "xs.append(3)", "print(len(xs))"] }, solution: { order: [0, 1, 2] }, explanation: "Create it, add to it, then measure it.", hints: ["Measure last."] },
            { type: "multiple_choice", prompt: 'xs[1] on ["a", "b", "c"] gives?', content: { options: ["b", "a", "c", "1"], correctIndex: 0 }, solution: { correctIndex: 0 }, explanation: "Index 1 is the second item.", hints: ["The second item."] },
          ],
        },
      ],
    },
    {
      title: "Unit 7 — Errors, Files & Modules",
      description: "Read tracebacks, handle failures, and use code others wrote",
      lessons: [
        {
          title: "Reading Errors",
          description: "What a traceback is telling you",
          xpReward: 15,
          exercises: [
            { type: "multiple_choice", prompt: "A traceback shows?", content: { options: ["The chain of calls that led to the error", "Only the fix", "Your list of files", "How long it took"], correctIndex: 0 }, solution: { correctIndex: 0 }, explanation: "Read it bottom-up: the last line is the error itself.", hints: ["It is a chain."] },
            { type: "multiple_choice", prompt: "ValueError means?", content: { options: ["Right type, wrong value", "Wrong type", "Missing file", "Bad indentation"], correctIndex: 0 }, solution: { correctIndex: 0 }, explanation: 'int("hi") is the right type but an unusable value.', hints: ["Right type, bad value."] },
            { type: "predict_output", prompt: "What happens when this runs?", content: { snippet: 'print(int("hi"))', options: ["ValueError", "0", "hi", "None"] }, solution: { answer: "ValueError" }, explanation: "int cannot convert hi, so it raises ValueError before printing anything.", hints: ["It raises."] },
            { type: "multiple_choice", prompt: 'Which error does 1 + "a" raise?', content: { options: ["TypeError", "ValueError", "NameError", "FileNotFoundError"], correctIndex: 0 }, solution: { correctIndex: 0 }, explanation: "You cannot add a number and a string together, so Python raises a TypeError.", hints: ["They are different types."] },
            { type: "multiple_choice", prompt: "NameError means?", content: { options: ["A name is not defined", "A file is missing", "A type is wrong", "A number is too big"], correctIndex: 0 }, solution: { correctIndex: 0 }, explanation: "Usually a typo, or a variable used before it exists.", hints: ["A missing name."] },
            { type: "multiple_choice", prompt: "The last line of a traceback tells you?", content: { options: ["The error type and message", "Your Python version", "The file size", "The fix"], correctIndex: 0 }, solution: { correctIndex: 0 }, explanation: "Start there, then read upward to see how you got there.", hints: ["The bottom line."] },
          ],
        },
        {
          title: "try and except",
          description: "Handling errors instead of crashing",
          xpReward: 15,
          exercises: [
            { type: "multiple_choice", prompt: "try/except lets you?", content: { options: ["Handle errors instead of crashing", "Run faster", "Skip indentation", "Delete errors"], correctIndex: 0 }, solution: { correctIndex: 0 }, explanation: "You catch the problem and decide what happens next.", hints: ["You catch it."] },
            { type: "fill_blank", prompt: "Catch the conversion error", content: { code: 'try:\n    n = int("hi")\n___ ValueError:\n    print("bad")', blank: "except", options: ["except", "catch", "rescue", "handle"] }, solution: { answer: "except" }, explanation: "except names the error you want to catch.", hints: ["It is not catch."] },
            { type: "predict_output", prompt: "What prints?", content: { snippet: 'try:\n    print(int("hi"))\nexcept ValueError:\n    print("bad")', options: ["bad", "hi", "ValueError", "Error"] }, solution: { answer: "bad" }, explanation: "The error is caught, so the except block runs.", hints: ["The handler prints."] },
            { type: "multiple_choice", prompt: "Code in a finally block runs?", content: { options: ["Always", "Only on error", "Only on success", "Never"], correctIndex: 0 }, solution: { correctIndex: 0 }, explanation: "finally runs either way, which makes it good for cleanup.", hints: ["Every time."] },
            { type: "multiple_choice", prompt: "Which one catches almost any error?", content: { options: ["except Exception:", "except Error:", "except All:", "except *:"], correctIndex: 0 }, solution: { correctIndex: 0 }, explanation: "Exception is the base class for most built-in errors.", hints: ["The base type."] },
            { type: "predict_output", prompt: "What prints?", content: { snippet: 'try:\n    print(1 / 0)\nexcept ZeroDivisionError:\n    print("no")', options: ["no", "0", "1.0", "ZeroDivisionError"] }, solution: { answer: "no" }, explanation: "Dividing by zero raises, and the handler prints no.", hints: ["It is caught."] },
          ],
        },
        {
          title: "Writing Files",
          description: "Open, write and always close",
          xpReward: 15,
          exercises: [
            { type: "multiple_choice", prompt: "Which one opens a file for writing?", content: { options: ['open("f.txt", "w")', 'open("f.txt")', 'open("f.txt", "r")', 'write("f.txt")'], correctIndex: 0 }, solution: { correctIndex: 0 }, explanation: "The mode tells Python what you plan to do.", hints: ["Set the mode."] },
            { type: "multiple_choice", prompt: "Why use with open(...) as f?", content: { options: ["It closes the file for you", "It runs faster", "It encrypts the file", "It prints the file"], correctIndex: 0 }, solution: { correctIndex: 0 }, explanation: "with closes the file even if an error happens inside.", hints: ["Automatic cleanup."] },
            { type: "fill_blank", prompt: "Write the text into the file", content: { code: 'with open("a.txt", "w") as f:\n    f.___("hi")', blank: "write", options: ["write", "print", "append", "put"] }, solution: { answer: "write" }, explanation: "write() puts text into the file.", hints: ["Five letters."] },
            { type: "multiple_choice", prompt: 'Mode "a" does what?', content: { options: ["Appends to the end", "Deletes the file", "Reads only", "Creates a folder"], correctIndex: 0 }, solution: { correctIndex: 0 }, explanation: "a adds to the end without erasing what is there.", hints: ["It adds on."] },
            { type: "multiple_choice", prompt: 'Mode "w" on a file that already has text?', content: { options: ["Overwrites everything in it", "Appends to it", "Raises an error", "Copies it"], correctIndex: 0 }, solution: { correctIndex: 0 }, explanation: "Be careful: w starts the file fresh.", hints: ["It starts fresh."] },
            { type: "multiple_choice", prompt: "Which habit keeps files safe?", content: { options: ["Always use with open(...)", "Leave files open", "Open inside a loop", "Never close them"], correctIndex: 0 }, solution: { correctIndex: 0 }, explanation: "The context manager always closes the file.", hints: ["The with statement."] },
          ],
        },
        {
          title: "Reading Files",
          description: "Read the whole file, or line by line",
          xpReward: 15,
          exercises: [
            { type: "multiple_choice", prompt: "Which method reads the whole file into a string?", content: { options: ["f.read()", "f.get()", "f.text()", "f.all()"], correctIndex: 0 }, solution: { correctIndex: 0 }, explanation: "read() returns everything at once.", hints: ["Four letters."] },
            { type: "fill_blank", prompt: "Read and print the whole file", content: { code: 'with open("a.txt") as f:\n    print(f.___())', blank: "read", options: ["read", "print", "text", "open"] }, solution: { answer: "read" }, explanation: "read() gives you the contents.", hints: ["Four letters."] },
            { type: "multiple_choice", prompt: "Looping over a file object gives you?", content: { options: ["One line at a time", "Bytes", "Whole words", "Nothing"], correctIndex: 0 }, solution: { correctIndex: 0 }, explanation: "for line in f is the memory-friendly way to read.", hints: ["One line each."] },
            { type: "multiple_choice", prompt: "The default open mode is?", content: { options: ["r — read", "w", "a", "x"], correctIndex: 0 }, solution: { correctIndex: 0 }, explanation: "Opening without a mode means read.", hints: ["Reading."] },
            { type: "predict_output", prompt: "What prints?", content: { snippet: 'lines = "a\\nb".splitlines()\nprint(len(lines))', options: ["2", "1", "3", "Error"] }, solution: { answer: "2" }, explanation: 'splitlines() splits on the newline, giving ["a", "b"].', hints: ["How many lines are there?"] },
            { type: "multiple_choice", prompt: "Why call strip() on each line?", content: { options: ["Lines from files end with a newline character", "It sorts them", "It uppercases them", "It deletes the file"], correctIndex: 0 }, solution: { correctIndex: 0 }, explanation: "strip() removes the trailing newline so comparisons work as expected.", hints: ["There is a hidden character."] },
          ],
        },
        {
          title: "Modules and pip",
          description: "Using code that other people wrote",
          xpReward: 20,
          exercises: [
            { type: "multiple_choice", prompt: "Which one imports a module?", content: { options: ["import math", "include math", "use math", "require math"], correctIndex: 0 }, solution: { correctIndex: 0 }, explanation: "import brings a module into your file.", hints: ["It is not include."] },
            { type: "multiple_choice", prompt: "pip is?", content: { options: ["Python's package installer", "A text editor", "A kind of loop", "A file format"], correctIndex: 0 }, solution: { correctIndex: 0 }, explanation: "pip installs libraries shared by the community.", hints: ["It installs things."] },
            { type: "fill_blank", prompt: "Import the math module", content: { code: "___ math\nprint(math.sqrt(16))", blank: "import", options: ["import", "include", "using", "load"] }, solution: { answer: "import" }, explanation: "After importing, math.sqrt(16) prints 4.0.", hints: ["Six letters."] },
            { type: "multiple_choice", prompt: "from math import sqrt lets you?", content: { options: ["Call sqrt(16) directly", "Only use math.sqrt", "Skip imports", "Run faster"], correctIndex: 0 }, solution: { correctIndex: 0 }, explanation: "It pulls just that one name into your file.", hints: ["The name becomes local."] },
            { type: "predict_output", prompt: "What prints?", content: { snippet: "import math\nprint(math.floor(3.7))", options: ["3", "4", "3.7", "Error"] }, solution: { answer: "3" }, explanation: "floor rounds down.", hints: ["Down, not up."] },
            { type: "multiple_choice", prompt: "Which command installs the requests library?", content: { options: ["pip install requests", "pip get requests", "import requests", "python requests --add"], correctIndex: 0 }, solution: { correctIndex: 0 }, explanation: "Install it with pip first, then import it in your code.", hints: ["Install first."] },
          ],
        },
      ],
    },
    {
      title: "Unit 8 — Python Mastery",
      description: "Classes, comprehensions, testing and a capstone",
      lessons: [
        {
          title: "Classes and Objects",
          description: "Building your own types",
          xpReward: 20,
          exercises: [
            { type: "multiple_choice", prompt: "Which one defines a class?", content: { options: ["class Dog:", "def Dog:", "object Dog:", "Dog = class()"], correctIndex: 0 }, solution: { correctIndex: 0 }, explanation: "class, then a capitalised name, then a colon.", hints: ["Five letters."] },
            { type: "fill_blank", prompt: "Complete the class definition", content: { code: "___ Dog:\n    pass", blank: "class", options: ["class", "def", "object", "new"] }, solution: { answer: "class" }, explanation: "pass is there because the body is empty for now.", hints: ["It is not def."] },
            { type: "multiple_choice", prompt: "d = Dog() does what?", content: { options: ["Creates an instance of Dog", "Defines the class", "Deletes Dog", "Prints Dog"], correctIndex: 0 }, solution: { correctIndex: 0 }, explanation: "Calling the class builds an object from it.", hints: ["It builds one."] },
            { type: "multiple_choice", prompt: "An object is?", content: { options: ["An instance built from a class", "Another name for a class", "A function", "A module"], correctIndex: 0 }, solution: { correctIndex: 0 }, explanation: "The class is the blueprint and the object is the thing you build from it.", hints: ["Blueprint and thing."] },
            { type: "predict_output", prompt: "What prints?", content: { snippet: "class C:\n    pass\nc = C()\nprint(type(c))", options: ["<class '__main__.C'>", "<class 'C'>", "C", "Error"] }, solution: { answer: "<class '__main__.C'>" }, explanation: "Your class lives in __main__ when you run the file directly.", hints: ["It includes __main__."] },
            { type: "multiple_choice", prompt: "Class names are usually written how?", content: { options: ["Capitalised", "lowercase", "ALL CAPS", "With numbers only"], correctIndex: 0 }, solution: { correctIndex: 0 }, explanation: "Dog, not dog.", hints: ["Like Dog."] },
          ],
        },
        {
          title: "Methods and __init__",
          description: "Setting up an object when it is created",
          xpReward: 20,
          exercises: [
            { type: "multiple_choice", prompt: "When does __init__ run?", content: { options: ["Automatically when you create an object", "Only when you call it yourself", "Never", "At the end of the file"], correctIndex: 0 }, solution: { correctIndex: 0 }, explanation: "It is the constructor.", hints: ["On creation."] },
            { type: "fill_blank", prompt: "Store the name on the object", content: { code: 'class Dog:\n    def __init__(self, name):\n        self.name = ___\nd = Dog("Rex")\nprint(d.name)', blank: "name", options: ["name", "self", '"Rex"', "Dog"] }, solution: { answer: "name" }, explanation: "Assign the parameter so each dog keeps its own name, and this prints Rex.", hints: ["The parameter."] },
            { type: "multiple_choice", prompt: "What does self refer to?", content: { options: ["The object being used", "The class file", "A global variable", "The module"], correctIndex: 0 }, solution: { correctIndex: 0 }, explanation: "self is how a method reaches its own object's data.", hints: ["Its own object."] },
            { type: "predict_output", prompt: "What prints?", content: { snippet: "class C:\n    def __init__(self):\n        self.x = 2\nc = C()\nprint(c.x)", options: ["2", "0", "None", "Error"] }, solution: { answer: "2" }, explanation: "__init__ ran at creation and stored x on the object.", hints: ["It was set at creation."] },
            { type: "multiple_choice", prompt: "A method is?", content: { options: ["A function defined inside a class", "A kind of loop", "A module", "A list"], correctIndex: 0 }, solution: { correctIndex: 0 }, explanation: "Same idea as a function, but attached to a class.", hints: ["A function in a class."] },
            { type: "multiple_choice", prompt: "Why does every instance method list self first?", content: { options: ["So it can read and write the object's own data", "To print things", "To import modules", "To make the class faster"], correctIndex: 0 }, solution: { correctIndex: 0 }, explanation: "The first argument always receives the object the method was called on.", hints: ["It is about the object."] },
          ],
        },
        {
          title: "Comprehensions",
          description: "Building lists and dicts in one line",
          xpReward: 20,
          exercises: [
            { type: "multiple_choice", prompt: "[x * 2 for x in [1, 2]] gives?", content: { options: ["[2, 4]", "[1, 2]", "[2]", "Error"], correctIndex: 0 }, solution: { correctIndex: 0 }, explanation: "Every item is doubled.", hints: ["Double each one."] },
            { type: "predict_output", prompt: "What prints?", content: { snippet: "print([x * x for x in range(3)])", options: ["[0, 1, 4]", "[0, 1, 2]", "[1, 4, 9]", "Error"] }, solution: { answer: "[0, 1, 4]" }, explanation: "0, 1 and 2 squared.", hints: ["Square each one."] },
            { type: "fill_blank", prompt: "Keep only the even numbers", content: { code: "print([x for x in range(4) if x % 2 == ___])", blank: "0", options: ["0", "1", "2", "x"] }, solution: { answer: "0" }, explanation: "Even numbers leave remainder 0, so this prints [0, 2].", hints: ["Evens leave no remainder."] },
            { type: "multiple_choice", prompt: "A comprehension is?", content: { options: ["A short way to build a list from a loop", "A type of function", "A file mode", "An error handler"], correctIndex: 0 }, solution: { correctIndex: 0 }, explanation: "Compact, and often easier to read than a loop.", hints: ["It builds a list."] },
            { type: "multiple_choice", prompt: "[n for n in [1, 2, 3] if n > 1] gives?", content: { options: ["[2, 3]", "[1]", "[1, 2, 3]", "[]"], correctIndex: 0 }, solution: { correctIndex: 0 }, explanation: "The filter keeps 2 and 3.", hints: ["Which ones are greater than 1?"] },
            { type: "predict_output", prompt: "What prints?", content: { snippet: "print({x: x * 2 for x in range(2)})", options: ["{0: 0, 1: 2}", "[0, 2]", "{0, 2}", "Error"] }, solution: { answer: "{0: 0, 1: 2}" }, explanation: "A dict comprehension builds keys and values together.", hints: ["Braces with colons."] },
          ],
        },
        {
          title: "Testing Your Code",
          description: "Proving your code works with assert and pytest",
          xpReward: 20,
          exercises: [
            { type: "multiple_choice", prompt: "What does assert do?", content: { options: ["Raises an error when the check is False", "Prints a test", "Installs pytest", "Skips the code"], correctIndex: 0 }, solution: { correctIndex: 0 }, explanation: "If the condition is False, the program stops with AssertionError.", hints: ["False means stop."] },
            { type: "multiple_choice", prompt: "pytest is?", content: { options: ["A test runner", "A web framework", "A database", "A text editor"], correctIndex: 0 }, solution: { correctIndex: 0 }, explanation: "It finds and runs your test functions for you.", hints: ["It runs tests."] },
            { type: "fill_blank", prompt: "Make the assertion pass", content: { code: "def add(a, b):\n    return a + b\n\nassert add(2, 3) == ___", blank: "5", options: ["5", "23", "6", "True"] }, solution: { answer: "5" }, explanation: "2 + 3 is 5.", hints: ["Add them."] },
            { type: "multiple_choice", prompt: "Why test edge cases?", content: { options: ["Bugs hide in empty, zero and negative inputs", "Tests run faster", "It looks tidy", "To skip logic"], correctIndex: 0 }, solution: { correctIndex: 0 }, explanation: "Normal input often hides the bug.", hints: ["Where bugs hide."] },
            { type: "multiple_choice", prompt: "Test function names usually start with?", content: { options: ["test_", "assert_", "check_", "try_"], correctIndex: 0 }, solution: { correctIndex: 0 }, explanation: "That prefix is how pytest discovers them.", hints: ["Four letters."] },
            { type: "multiple_choice", prompt: "A failing assert means?", content: { options: ["Your expectation did not hold", "Python is broken", "The file is missing", "The test passed"], correctIndex: 0 }, solution: { correctIndex: 0 }, explanation: "Good news — you found a bug early.", hints: ["The check failed."] },
          ],
        },
        {
          title: "Capstone: Ship a Real Program",
          description: "Plan, build and verify a small to-do app",
          xpReward: 20,
          exercises: [
            { type: "ai_prompt", prompt: "Plan your capstone with the AI", content: { scenario: 'Capstone plan: ask the AI to break a command-line to-do list into 3 small steps. Your program should keep the todos in a list and print them with a loop.', aiTask: "You are Codingo, a friendly tutor for absolute beginners. Break the learner's project into exactly 3 short numbered steps mentioning a list and a loop. Under 90 words, simple. The learner asked:", placeholder: "e.g. Break a command-line to-do app into 3 steps using a list and a loop", checklist: ["Does the plan have numbered steps?", "Does it mention a list or a loop?"], exampleAnswer: '1. Create an empty list called todos to hold your tasks. 2. Add tasks with todos.append("task") and print how many you have. 3. Loop over them with for t in todos: and print each one, then run it and test.' }, solution: { checklist: [true, true] }, explanation: "You planned it with the AI and stayed in charge of the design.", hints: ["Ask for 3 steps plus a list or loop."] },
            { type: "multiple_choice", prompt: "Which one keeps a to-do list in memory?", content: { options: ["a list of strings", "a single string", "a number", "a class called Print"], correctIndex: 0 }, solution: { correctIndex: 0 }, explanation: "A list holds the tasks in order.", hints: ["Something ordered."] },
            { type: "arrange", prompt: "Order these lines to print every todo", content: { blocks: ["todos = []", 'todos.append("Learn Python")', "for t in todos:", "    print(t)"] }, solution: { order: [0, 1, 2, 3] }, explanation: "Create the list, fill it, then loop and print.", hints: ["Fill it before looping."] },
            { type: "predict_output", prompt: "What prints?", content: { snippet: 'todos = []\ntodos.append("a")\ntodos.append("b")\nprint(len(todos))', options: ["2", "1", '["a", "b"]', "Error"] }, solution: { answer: "2" }, explanation: "Two tasks were added.", hints: ["Count the appends."] },
            { type: "multiple_choice", prompt: "Best next step after this course?", content: { options: ["Build one small project of your own", "Stop coding", "Re-read every lesson", "Only watch videos"], correctIndex: 0 }, solution: { correctIndex: 0 }, explanation: "Projects turn knowledge into skill.", hints: ["Build something."] },
            { type: "multiple_choice", prompt: "Which is the honest expert habit?", content: { options: ["Understand the code you ship", "Copy without reading", "Skip testing", "Never ask questions"], correctIndex: 0 }, solution: { correctIndex: 0 }, explanation: "Understanding compounds; copying evaporates.", hints: ["Understand it."] },
          ],
        },
      ],
    },
  ],
};
